server:
  port: 10086
spring:
  rabbitmq:
    host: 192.168.243.134
    username: root
    password: root
    virtual-host: b2c
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
    publisher-confirms: true
  application:
    name: b2c-registry
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护