server:
  port: 10010
spring:
  application:
    name: api-gateway
  rabbitmq:
    host: 192.168.243.134
    username: root
    password: root
    virtual-host: b2c
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  ignored-services:
    - upload-service # 忽略upload-service服务
  ignored-patterns: /upload/**
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order /**
  add-host-header: true #添加host域信息到头信息
  sensitive-headers:
ribbon:
  ConnectTimeout: 50000 # 连接超时时间(ms)
  ReadTimeout: 50000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 # 熔断超时时长：10000ms
b2c:
  jwt:
    pubKeyPath: E:\mr\b2c-auth-key\rea.pub # 公钥地址
    cookieName: B2C_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/item